2014139865-API/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using _2014139865_API.Areas.HelpPage.ModelDescriptions;
using _2014139865_API.Areas.HelpPage.Models;

namespace _2014139865_API.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

2014139865-API/Controllers/EnsambladorasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using _2014139865_ENT;
using _2014139865_PER;

namespace _2014139865_API.Controllers
{
    public class EnsambladorasController : ApiController
    {
        private EnsambladoraDbContext db = new EnsambladoraDbContext();

        // GET: api/Ensambladoras
        public IQueryable<Ensambladora> GetEnsambladoras()
        {
            return db.Ensambladoras;
        }

        // GET: api/Ensambladoras/5
        [ResponseType(typeof(Ensambladora))]
        public IHttpActionResult GetEnsambladora(int id)
        {
            Ensambladora ensambladora = db.Ensambladoras.Find(id);
            if (ensambladora == null)
            {
                return NotFound();
            }

            return Ok(ensambladora);
        }

        // PUT: api/Ensambladoras/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutEnsambladora(int id, Ensambladora ensambladora)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != ensambladora.EnsambladoraId)
            {
                return BadRequest();
            }

            db.Entry(ensambladora).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EnsambladoraExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Ensambladoras
        [ResponseType(typeof(Ensambladora))]
        public IHttpActionResult PostEnsambladora(Ensambladora ensambladora)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Ensambladoras.Add(ensambladora);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = ensambladora.EnsambladoraId }, ensambladora);
        }

        // DELETE: api/Ensambladoras/5
        [ResponseType(typeof(Ensambladora))]
        public IHttpActionResult DeleteEnsambladora(int id)
        {
            Ensambladora ensambladora = db.Ensambladoras.Find(id);
            if (ensambladora == null)
            {
                return NotFound();
            }

            db.Ensambladoras.Remove(ensambladora);
            db.SaveChanges();

            return Ok(ensambladora);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool EnsambladoraExists(int id)
        {
            return db.Ensambladoras.Count(e => e.EnsambladoraId == id) > 0;
        }
    }
}

2014139865-API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NOMBREE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Cinturones", "Index", "Cinturones")</li>
                    <li>@Html.ActionLink("Asientos", "Index", "Asientos")</li>
                    <li>@Html.ActionLink("Volantes", "Index", "Volantes")</li>
                    <li>@Html.ActionLink("Parabrisas", "Index", "Parabrisas")</li>
                    <li>@Html.ActionLink("Ensambladora", "Index", "Ensambladoras")</li>
                    <li>@Html.ActionLink("Propietarios", "Index", "Propietarios")</li>
                    <li>@Html.ActionLink("Llantas", "Index", "Llantas")</li>
                    <li>@Html.ActionLink("Automoviles", "Index", "Automoviles")</li>
                    <li>@Html.ActionLink("Buses", "Index", "Buses")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>